server:
  port: 8082
  host: localhost

psql:
  host: localhost
  port: 5432
  username: ilyasukharev
  database: vseznaika-user-service
  ssl_mode: disable
  max_transaction_retries: 3
  max_open_connections: 50
  max_idle_connections: 10
  max_lifetime_connections_min: 60
  migration_file_path: file://resources/migration

rediska:
  address: "localhost:6379"
  db: 0

default_client:
  timeout: 180
  MaxIdleConn: 50
  MaxIdleConnPerHost: 10
  IdleConnTimeout: 90

services:
  youkassa:
    url: https://api.yookassa.ru
  user_service:
    url: http://localhost:8081
  subscription_service:
    url: http://localhost:8083
  front:
    payment_link: http://192.168.1.183:3000/payment?id=%s

