CREATE TYPE user_type AS ENUM (
    'ADMIN',
    'CONTENT_CREATOR',
    'PARENT'
    );

create table if not exists users
(
    id            uuid unique primary key,
    first_name    varchar     not null,
    last_name     varchar     null,
    middle_name   varchar     null,
    email         varchar     not null unique,
    phone         varchar     null unique,
    notifications bool        not null default true,
    type          user_type   not null,
    child_name    varchar     null,
    child_age     int         null,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz,
    deleted_at    timestamptz

        CONSTRAINT check_has_child
            CHECK (
                type <> 'PARENT'
                    OR (
                    child_name IS NOT NULL
                        AND btrim(child_name) <> ''
                        AND child_age BETWEEN 1 AND 18
                    )
                )
);

create table if not exists referrals
(
    id          int generated by default as identity primary key,
    referrer_id uuid        not null references users (id),
    referee_id  uuid        not null unique references users (id),
    confirmed   bool        not null default false,
    created_at  timestamptz not null default now(),

    CONSTRAINT check_not_self_referral
        CHECK (referrer_id <> referee_id)
);