CREATE TYPE user_type AS ENUM (
    'ADMIN',
    'CONTENT_CREATOR',
    'PARENT'
    );

CREATE TYPE male AS ENUM (
    'MALE',
    'FEMALE'
    );

create table if not exists users
(
    id            uuid unique primary key,
    first_name    varchar     not null,
    last_name     varchar     null,
    middle_name   varchar     null,
    email         varchar     not null unique,
    phone         varchar     null unique,
    notifications bool        not null default true,
    type          user_type   not null,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz,
    deleted_at    timestamptz
);
create index idx_user_phone on users(phone);

create table if not exists referrals
(
    id          int generated by default as identity primary key,
    referrer_id uuid        not null references users (id),
    referee_id  uuid        not null unique references users (id),
    confirmed   bool        not null default false,
    created_at  timestamptz not null default now(),

    CONSTRAINT check_not_self_referral
        CHECK (referrer_id <> referee_id)
);

create index idx_ref_referrer_id on referrals(referrer_id);

create table if not exists children
(
    id         uuid unique primary key default gen_random_uuid(),
    parent_id  uuid      not null references users (id),
    name       varchar   not null,
    age        int       not null,
    gender     male,
    birthday   date,
    created_at timestamp not null      default now(),
    updated_at timestamp,
    deleted_at timestamp
);

create index idx_child_parent_id on children(parent_id);